# 0.2.2 The 20newsgroups dataset

In [1]:
%load_ext autoreload
%autoreload 2

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import fetch_20newsgroups_vectorized

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings("ignore")

In [3]:
import sys
sys.path.append("../../../../") 

import utils.paths as path
from utils.paths2 import direcciones

## 0.2.2.1 The 20newsgroups dataset

https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html#sklearn.datasets.fetch_20newsgroups

Este dataset contiene la información de 18.846 mensages clasificados en 20 categorías. El dataset se encuentra dividido en un conjunto de entrenamiento y un conjunto de prueba. La partición de los dos conjuntos se baso en la fecha en la cual se publicó el mensaje únicamente.

In [4]:
bunch = fetch_20newsgroups(
    # -----------------------------------------------------
    # Specify another download and cache folder for the
    # datasets. By default all scikit-learn data is stored
    # in ‘~/scikit_learn_data’ subfolders.
    data_home=None,
    # -----------------------------------------------------
    # Select the dataset to load: ‘train’ for the training
    # set, ‘test’ for the test set, ‘all’ for both, with
    # shuffled ordering.
    subset="all",
    # -----------------------------------------------------
    # If None (default), load all the categories. If not
    # None, list of category names to load (other
    # categories ignored).
    categories=None,
    # -----------------------------------------------------
    # Whether or not to shuffle the data
    shuffle=False,
    # -----------------------------------------------------
    # Determines random number generation for dataset
    # shuffling.
    random_state=None,
    # -----------------------------------------------------
    # May contain any subset of (‘headers’, ‘footers’,
    # ‘quotes’). Each of these are kinds of text that will
    # be detected and removed from the newsgroup posts,
    # preventing classifiers from overfitting on metadata.
    #
    # ‘headers’ removes newsgroup headers, ‘footers’ removes
    # blocks at the ends of posts that look like signatures,
    # and ‘quotes’ removes lines that appear to be quoting
    # another post.
    #
    # ‘headers’ follows an exact standard; the other filters
    # are not always correct.
    remove=(),
    # -----------------------------------------------------
    # If True, returns (data, target) instead of a Bunch
    # object.
    return_X_y=False,
)

bunch.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [5]:
bunch.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [6]:
bunch.target[:5]

array([ 9,  4, 11,  4,  0])

In [7]:
print(bunch.data[0])

From: cubbie@garnet.berkeley.edu (                               )
Subject: Re: Cubs behind Marlins? How?
Article-I.D.: agate.1pt592$f9a
Organization: University of California, Berkeley
Lines: 12
NNTP-Posting-Host: garnet.berkeley.edu


gajarsky@pilot.njin.net writes:

morgan and guzman will have era's 1 run higher than last year, and
 the cubs will be idiots and not pitch harkey as much as hibbard.
 castillo won't be good (i think he's a stud pitcher)

       This season so far, Morgan and Guzman helped to lead the Cubs
       at top in ERA, even better than THE rotation at Atlanta.
       Cubs ERA at 0.056 while Braves at 0.059. We know it is early
       in the season, we Cubs fans have learned how to enjoy the
       short triumph while it is still there.



In [8]:
X, y = fetch_20newsgroups(
    # -----------------------------------------------------
    # If True, returns (data, target) instead of a Bunch
    # object.
    return_X_y=True,
)

display(
    X[:2],
    y[:2],
)

["From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n",
 "From: guykuo@carson.u.washington.edu (Guy Kuo)\nSubject: SI Clock Poll - Final Call\nSummary: Final call for SI clock reports\nKeywords: SI,acceleration,clock,upgrade\nArticle-I.D.: shelley.1qvfo9INNc3s\nOrganization: University of Washington\nLines: 

array([7, 4])

In [ ]:
bunch = fetch_20newsgroups_vectorized(
    # -----------------------------------------------------
    # Specify another download and cache folder for the
    # datasets. By default all scikit-learn data is stored
    # in ‘~/scikit_learn_data’ subfolders.
    data_home=None,
    # -----------------------------------------------------
    # Select the dataset to load: ‘train’ for the training
    # set, ‘test’ for the test set, ‘all’ for both, with
    # shuffled ordering.
    subset="all",
    # -----------------------------------------------------
    # May contain any subset of (‘headers’, ‘footers’,
    # ‘quotes’). Each of these are kinds of text that will
    # be detected and removed from the newsgroup posts,
    # preventing classifiers from overfitting on metadata.
    #
    # ‘headers’ removes newsgroup headers, ‘footers’ removes
    # blocks at the ends of posts that look like signatures,
    # and ‘quotes’ removes lines that appear to be quoting
    # another post.
    #
    # ‘headers’ follows an exact standard; the other filters
    # are not always correct.
    remove=(),
    # -----------------------------------------------------
    # If True, returns (data, target) instead of a Bunch
    # object.
    return_X_y=False,
)

In [13]:
bunch.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [15]:
bunch.target

array([ 9,  4, 11, ...,  4,  6,  7])

In [ ]:
print('ok_')

ok_
